[package]
name = "pliron-common-dialects"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/pliron-org/pliron-common-dialects"
categories = ["compilers"]
keywords = ["pliron", "mlir", "dialect", "compiler"]

[dependencies]
pliron = { git = "https://github.com/pliron-org/pliron.git" }
pliron-llvm = { git = "https://github.com/pliron-org/pliron.git" }
thiserror = "2"
expect-test = "1"

[dev-dependencies]
env_logger = "0"